### ISSUE TITLE
"Device not found" on macOS

### ISSUE THREAD

**Issue by nalzok** [webfpga/cli#2]
I got the following error when trying out the command line tool on macOS Mojave

```
$ python flash.py bitstream.bin
Traceback (most recent call last):
  File "flash.py", line 189, in <module>
    main()
  File "flash.py", line 180, in main
    flasher = Flasher()
  File "flash.py", line 68, in __init__
    raise ValueError('Device not found')
ValueError: Device not found
```

A quick look at `ls /dev/cu.*` didn't reveal any new device, but I have no problem using your online IDE at https://beta.webfpga.io. Do I need to install a driver or something?

**Comment by ryanmjacobs** [comment]
Hmm... Could you check `dmesg` to see how the OS is picking up the device?

```console
$ dmesg --follow
...
[ 1437.328119] usb 2-1: new full-speed USB device number 5 using xhci_hcd
[ 1437.470267] usb 2-1: New USB device found, idVendor=16d0, idProduct=0e6c, bcdDevice= 2.00
[ 1437.470273] usb 2-1: New USB device strings: Mfr=1, Product=2, SerialNumber=3
[ 1437.470277] usb 2-1: Product: Cascadia WebUSB FPGA Programmer
[ 1437.470280] usb 2-1: Manufacturer: Auburn Ventures, LLC
[ 1437.470283] usb 2-1: SerialNumber: 2039393F4B4D
[ 1437.492488] hidraw: raw HID events driver (C) Jiri Kosina
[ 1437.497687] usbcore: registered new interface driver usbhid
[ 1437.497688] usbhid: USB HID core driver
```

The identification should be ` idVendor=16d0, idProduct=0e6c`.

**Comment by nalzok** [comment]
It's kinda weird that the `--follow` flag doesn't seem to be available on macOS

```
$ dmesg --follow
usage: sudo dmesg

$ sudo dmesg --follow
usage: sudo dmesg
```

I did a `sudo dmesg`, but couldn't find the identification, or any USB device

```
$ sudo dmesg | grep 'idVendor=16d0, idProduct=0e6c'


$ sudo dmesg | grep 'New USB device found'


```

Here is the output of `sudo dmesg > dmesg.txt`, for your information

[dmesg.txt](https://github.com/webfpga/cli/files/3587172/dmesg.txt)

**Edit**:

I guess the FPGA programmer is recognized

```
$ ioreg -p IOUSB -w0
+-o Root  <class IORegistryEntry, id 0x100000100, retain 15>
  +-o AppleUSBXHCI Root Hub Simulation@14000000  <class AppleUSBRootHubDevice, id 0x100002a31, registered, matched, active, busy 0 (2 ms), retain 9>
    +-o Cascadia WebUSB FPGA Programmer@14300000  <class AppleUSBDevice, id 0x100007956, registered, matched, active, busy 0 (1 ms), retain 9>

$ system_profiler SPUSBDataType
USB:

    USB 3.0 Bus:

      Host Controller Driver: AppleUSBXHCISPTLP
      PCI Device ID: 0x9d2f
      PCI Revision ID: 0x0021
      PCI Vendor ID: 0x8086

        Cascadia WebUSB FPGA Programmer:

          Product ID: 0x0e6c
          Vendor ID: 0x16d0
          Version: 2.00
          Serial Number: 2045353C4150
          Speed: Up to 12 Mb/sec
          Manufacturer: Auburn Ventures, LLC
          Location ID: 0x14300000 / 44
          Current Available (mA): 500
          Extra Operating Current (mA): 0

    USB 3.1 Bus:

      Host Controller Driver: AppleUSBXHCIAR
      PCI Device ID: 0x15d4
      PCI Revision ID: 0x0002
      PCI Vendor ID: 0x8086
      Bus Number: 0x00
```

**Comment by ryanmjacobs** [comment]
Huh that is weird. You don’t really need the follow flag; it’s just helpful.

I don’t see any usb references in that list. Can you remove and reinsert
the device? Then run dmesg again. It should show up.

**Comment by nalzok** [comment]
The USB device still doesn't appear after I re-insert it, but `python flash.py bitstream.bin` works! Do I still need to worry about this issue?

```
$ python flash.py bitstream.bin
Config 1
	Interface 0,0
		Endpoint 129
AT: Hi
API: C_WEBUSB+
APR: 010106
Found programmer.
Checking for FPGA module and its flash configuration...
APWE: wren
AMQ: SA016WHEe
AMBE: DONE
AMQ: SA016WHEE
AMW: OK
02ff812d452b5361745f30375f5365705f323031
395f30323a33313a31375f504d5f5554432b7368
61737461706c75738103ff3681067eaa997e5181
RESPONSE => 61

040105928109206202b372015082820211810301
018b021086024085020186020486021086024084
02108602408502018602048602108602408c0202
860208
RESPONSE => 64

8602208602808502028602088402028602088602
20860280850202860208ffffffffffffffffffca
040c3020d402c3d5040c3020d402c3d5040c3020
d402c3
RESPONSE => 64

d5040c3020d402c3d5040c3020d402c3d5040c30
20d402c3d5040c3020d402c3d5040c3020d402c3
d5040c3020d402c3d5040c3020d402c3d5040c30
20d4
RESPONSE => 63

02c3d5040c3020d402c3d5040c3020d402c3d504
0c3020d402c3d5040c3020d402c3d5040c3020a4
b002c3d5040c3020d402c3d5040c3020d402c3d5
RESPONSE => 61

040c3020d402c3d5040c3020d402c3d5040c3020
d402c3d5040c3020d402c3d5040c3020d402c3d5
040c3020d402c3d5040c3020d402c3d5040c3020
d402c3
RESPONSE => 64

d5040c3020d402c3d5040c3020d402c3d5040c30
20d402c3d5040c3020d402c3d5040c3020d402c3
d5040c3020d402c3ffffffffffffffffffff89ff
ffffff
RESPONSE => 64

ffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffa0fff7040c3020d402c3d504
0c3020d402c3d5040c3020d402c3d5040c3020d4
02c3d5
RESPONSE => 64

040c3020d402c3d5040c3020d402c3d5040c3020
d402c3d5040c3020d402c3ffffffffffffffffff
ffffffffffffffffffffff8bffffffffffffffff
ffffff
RESPONSE => 64

ffffffffffffffffffffffffff96040c3020d402
c3d5040c3020d402c3d5040c3020d402c3d5040c
3020d402c3d5040c3020d402c3d5040c3020d402
c3c98c
RESPONSE => 64

040c3020d402c3d5040c3020d402c3ffffffffff
ffffffffffffffffffffffffffffffffffffffff
ffffffffff8dffffffffffffffffffffffffffff
94
RESPONSE => 62

040c3020d402c3d5040c3020d402c3d5040c3020
d402c3d5040c3020d402c3d5040c3020d402c3d5
040c3020d402c3d5040c3020d402c3d5040c3020
d402c3
RESPONSE => 64

d5040c3020d402c3d5040c3020d402c3d5040c30
20d402c3d5040c3020d402c3d5040c3020d402c3
d5040c3020aea602c3d5040c3020d402c3d5040c
3020d4
RESPONSE => 64

02c3d002018202728106b0110101018b02108602
4085020186020486021086024084021086024085
02018602048602108602408c0202860208860220
860280
RESPONSE => 64

8502028602088402028602088602208602808502
02860208d20240d90204ffff830201ffad0202ff
ffffffe9030c30d503c302d4030c30d503c302d4
030c30
RESPONSE => 64

d503c302d4030c30d503c302d4030c30d503c302
d4030c30d503c302d4030c30d503c302d4030c30
d503c302d4030c30d503c302d4030c30d503c302
d4
RESPONSE => 62

030c30d503c302d4030c30d503c302d4030c30d5
03c302c490030c30d503c302d4030c30d503c302
d4030c30d503c302d4030c30d503c302d4030c30
d5
RESPONSE => 62

03c302d4030c30d503c302d4030c30d503c302d4
030c30d503c302d4030c30d503c302d4030c30d5
03c302d4030c30d503c302d4030c30d503c302d4
030c30
RESPONSE => 64

d503c302d4030c30d503c302d4030c30d503c302
d4030c30d503c302d4030c30d503c302d4030c30
d503c302d4030c30d503c302fffffffffffff3ff
ffffff
RESPONSE => 64

ffffffffffffffffffffffffffffffffffffffff
ffffffffffffffffa0ffffffffff8c030c30d503
c302d4030c30d503c302d4030c30d503c302d403
0c30d5
RESPONSE => 64

03c302d4030c30d503c302d4030c30d503c302d4
030c30d503c302d4030c30d503c302d4030c30d5
03c302d4030c30d503c302d4030c30d503c302d4
030c30
RESPONSE => 64

d503c302d4030c30d503c302d4030c30d503c302
d4030c30d503c302d4030c30d503c302d2087201
5011020101880202860208860220860280850202
850280
RESPONSE => 64

8502028602088602208602808502028602088d02
1086024085020186020486021084020486021086
0240850201860204860210860240fffffffeffff
ffffff
RESPONSE => 64

c9041030c0d403030cd4041030c0d403030cd404
1030c0d403030cd4041030c0d403030cd4041030
c0d403030cd4041030c0d403030cd4041030c0d4
03030c
RESPONSE => 64

d4041030c0d403030cd4041030c0d403030cd404
1030c0d403030cd4041030c0d403030cd4041030
c0d403030cd4041030c0d403030cd4041030c0d4
03030c
RESPONSE => 64

d4041030c0d403030cd4041030c0d403030cd404
1030c0d403030cd4041030c0d403030cd4041030
c0d403030cd4041030c0d403030c8cc8041030c0
d4
RESPONSE => 62

03030cd4041030c0d403030cd4041030c0d40303
0cd4041030c0d403030cd4041030c0d403030cd4
041030c0d403030cd4041030c0d403030cd40410
30c0d4
RESPONSE => 64

03030cd4041030c0d403030cd4041030c0d40303
0cd4041030c0d403030cd4041030c0d403030cff
ffffffffffffffffffffffffffffffffffffffff
ffffff
RESPONSE => 64

ffffffffffffffffffffffffffffffffffffffff
a0041030c0d403030cd4041030c0d403030cd404
1030c0d403030cc98b041030c0d403030cd40410
30c0d4
RESPONSE => 64

03030cd4041030c0d403030cd4041030c0d40303
0cd4041030c0d403030cffffffffffffffffffff
ffffffffffffffffffffffffffffffff82ffffff
ffffff
RESPONSE => 64

ffffffffffffffffffffffffffffffffffffffff
ffffffffffffa0ffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffffffa0
ffffff
RESPONSE => 64

ffffffffff9c041030c0d403030cd4041030c0d4
03030cd4041030c0d403030cd4041030c0d40303
0cd4041030c0d403030cd4041030c0d403030cd4
RESPONSE => 61

041030c0d403030cd4041030c0d403030cd40410
30c0d403030cd4041030c0d403030cd4041030c0
d403030cd4041030c0d403030cd4041030c0d403
030cd4
RESPONSE => 64

041030c0d403030cd4041030c0d403030cd40410
30c0d403030cd602728106b01103010188020286
0208860220860280850202850280850202860208
8a0210
RESPONSE => 64

8202808502028602088d02108602408502018602
0486021084020486021086024085020186020486
0210860240c50220a4ad0202da0210d202c0ffff
850204
RESPONSE => 64

ffffdc020effff9d0330c0c30209850304208102
20860401030cc4021084020281034002880330c0
bf0420014085036904810220880401030cc10314
c884
RESPONSE => 63

062691780640890330c0c702698b0401030cc704
3691688b0330c0c302108302698b0401030cc303
018082043691788b0330c0c70369048a0401030c
c7
RESPONSE => 62

05369128068a0330c0c704690404890401030cc3
0258830536912a608a0330c0c1031f8584026982
0224810210860401030cc105066b81a082043691
3881
RESPONSE => 63

034007880330c0c60320698b0401030cc30301a0
82043691388b0330c0c0053fc7e0898204046904
810220810220860401030cc00603bede181082
RESPONSE => 60

07369178604003880330c0c0053ff5cd9b830369
04810220880401030cc00603bdee718082063691
680640890330c0bf03803382021b830269820228
88
RESPONSE => 62

0401030cbf07010b316001808204369168810240
890330c0c203c9098302698b0401030cbf020181
0510c980f082043691788b0330c0c0043fc3b184
RESPONSE => 61

04690404890401030cbf070103bc7b9980820536
912a068a0330c0c0053fdcf00a83046904048904
01030cc00603bcea5810820536912a608a0330c0
c20205
RESPONSE => 64

820204810269840210860401030cc30801a001c0
369138820207880330c0c30210820320698b0401
030cc402a082043691388b0330c0c2020d840369
0481
RESPONSE => 63

0220810220860401030cc7073691786040038803
30c0ab95043fef9084036904810220880401030c
c00403bc5f84063691680640890330c0c7026982
022888
RESPONSE => 64

0401030cc7043691688b0330c0c2020d8402698b
0401030cc7043691788b0330c0c7046904048904
01030cc70536912a068a0330c0c7046904048904
01030c
RESPONSE => 64

c70536912a608a0330c0c2020584026984021086
0401030cc302808304369138820207880330c0c6
0340698b0401030cc3025883043691388b0330c0
d3
RESPONSE => 62

0401030cc50220860280880330c0d30401030cd5
0330c0d30401030cd50330c0d30401030cd50330
c0d30401030cd50330c0d30401030cd50330c0d3
RESPONSE => 61

0401030cd50330c0d30401030cffffffffffffff
ffffffffffebffffffffffffffffffffffffffff
ffffffffffffffffffffffffffffffffffb50330
c0d3
RESPONSE => 63

0401030c92c30330c0d30401030cd50330c0d304
01030cd50330c0d30401030cd50330c0d3040103
0cd50330c0d30401030cd50330c0d30401030cd5
0330c0
RESPONSE => 64

d30401030cd50330c0d30401030cd50330c0d304
01030cd50330c0d30401030cd50330c0d3040103
0cd50330c0d30401030cd50330c0d30401030cd5
0330c0
RESPONSE => 64

d30401030cd50330c0d30401030cd6026281039f
728103801181028282030103ffffffffffffffff
ffffff97fffffffffffffffffe02828104800103
ffffff
RESPONSE => 64

ffffffffffffffffffffffffffffffffff960262
81054f11018282030103fffffbffffffffffffff
9002828104800103ffffffffffffffffffff8c02
6281
RESPONSE => 63

059f11028282030103ffffffffffffffffffffff
fffffff4ffffffffffa102828104800103ffffff
ffffffffffffffffffffffffffffffffff960262
81
RESPONSE => 62

054f11038282030103ffffffffffffd9ffffffb2
02828104800103ffffffffffffffffffff8c0322
578103010681
RESPONSE => 47

Flashing complete
```

**Comment by ryanmjacobs** [comment]
I suppose not. Glad your device is working!
